/*
* generated by Xtext
*/
package org.epclet.ui.contentassist;

import org.epclet.ui.contentassist.AbstractEPCletProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EPCletProposalProvider extends AbstractEPCletProposalProvider {

}
