/*
 * generated by Xtext
 */
package org.epclet;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EPCletRuntimeModule extends org.epclet.AbstractEPCletRuntimeModule {
  
}
